
public class Ingresos extends javax.swing.JFrame {

    /**
     * Creates new form Ingresos
     */
    public Ingresos() {
        initComponents();
        setSize(300,350);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbodega = new javax.swing.JButton();
        btnResponsable = new javax.swing.JButton();
        btnDepartamento = new javax.swing.JButton();
        btnpro = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnbodega.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnbodega.setText("INGRESAR BODEGA");
        btnbodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbodegaActionPerformed(evt);
            }
        });
        getContentPane().add(btnbodega);
        btnbodega.setBounds(50, 46, 191, 30);

        btnResponsable.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnResponsable.setText("INGRESO RESPONSABLE");
        btnResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsableActionPerformed(evt);
            }
        });
        getContentPane().add(btnResponsable);
        btnResponsable.setBounds(50, 169, 191, 30);

        btnDepartamento.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnDepartamento.setText("INGRESO DEPARTAMENTO");
        btnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartamento);
        btnDepartamento.setBounds(50, 128, 191, 30);

        btnpro.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnpro.setText("INGRESO PRODUCTO");
        btnpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproActionPerformed(evt);
            }
        });
        getContentPane().add(btnpro);
        btnpro.setBounds(50, 90, 190, 23);

        btnvolver.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnvolver.setText("VOLVER");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver);
        btnvolver.setBounds(97, 232, 90, 23);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("INGRESOS DE DATOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(69, 11, 149, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-80, 0, 550, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbodegaActionPerformed
        CrearBodega men = new CrearBodega();
        men.setVisible(true);
    }//GEN-LAST:event_btnbodegaActionPerformed

    private void btnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentoActionPerformed
        IngresarDepartamento men = new IngresarDepartamento();
        men.setVisible(true);
    }//GEN-LAST:event_btnDepartamentoActionPerformed

    private void btnResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsableActionPerformed
        CrearResponsable men = new CrearResponsable();
        men.setVisible(true);
    }//GEN-LAST:event_btnResponsableActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproActionPerformed
        IngresarProductos men = new IngresarProductos();
        men.setVisible(true);
    }//GEN-LAST:event_btnproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnResponsable;
    private javax.swing.JButton btnbodega;
    private javax.swing.JButton btnpro;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
